INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (1, 0, 0, 1.4, false, 0, 1, 1, null);
INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (3, 397, 33, 0.5, true, 0, 1, 2, null);
INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (4, 362, 89, 0.5, true, 0, 1, 2, null);
INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (5, 367, 59, 0.027, true, 0, 1, 3, null);
INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (6, 402, 59, 0.027, true, 0, 1, 3, null);
INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (7, 367, 115, 0.027, true, 0, 1, 3, null);
INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (8, 362, 33, 0.2, true, 0, 1, 4, null);
INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (9, 397, 33, 0.2, true, 0, 1, 4, null);
INSERT INTO public.subject (id, position_x, position_y, scale, editable, rotation, floor_id, subject_template_id, utilities) VALUES (10, 362, 89, 0.2, true, 0, 1, 4, null);